# Generated by Django 2.1.4 on 2019-01-07 13:47

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('auth_user', '0003_auto_20190107_1631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userabstract',
            table=None,
        ),
    ]
