# Generated by Django 2.1.4 on 2019-01-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190108_1729'),
        ('auth_user', '0004_auto_20190107_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='userabstract',
            name='competition',
            field=models.ManyToManyField(blank=True, to='api.Competition', verbose_name='Конкурсы, в которых он является судьей'),
        ),
    ]
