# Generated by Django 2.1.7 on 2019-02-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_userabstract_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userabstract',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер учатника в конкурсе'),
        ),
    ]
