# Generated by Django 2.1.7 on 2019-02-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_userabstract_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userabstract',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='userabstract',
            name='number',
        ),
    ]
