# Generated by Django 2.1.4 on 2019-01-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='number',
            field=models.PositiveIntegerField(blank=True, verbose_name='Место в конкурсе'),
        ),
    ]
