# Generated by Django 2.1.4 on 2019-01-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190102_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('PAIR_CONTEST', 'Парный конкурс'), ('ASSOCIATION_COMPETITION', 'Конкурс-ассоциации')], default='PAIR_CONTEST', max_length=50, verbose_name='Тип конкурса'),
        ),
    ]
