# Generated by Django 2.1.4 on 2019-01-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190102_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], default='MALE', max_length=50, verbose_name='Пол'),
        ),
    ]
