# Generated by Django 2.1.4 on 2019-01-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190102_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='competition',
        ),
        migrations.AddField(
            model_name='judge',
            name='competition',
            field=models.ManyToManyField(blank=True, null=True, to='api.Competition', verbose_name='Идентификатор конкурса'),
        ),
    ]
