# Generated by Django 2.1.4 on 2019-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190104_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в конкурсе'),
        ),
    ]
