# Generated by Django 2.1.4 on 2019-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190104_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='school_name',
            field=models.CharField(max_length=50, verbose_name='Название школы'),
        ),
    ]
