# Generated by Django 2.1.4 on 2019-01-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190104_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Competition', verbose_name='Конкурс'),
        ),
    ]
