# Generated by Django 2.1.4 on 2019-01-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='user_type',
            field=models.CharField(choices=[('JUDGE', 'Судья'), ('OBSERVER', 'Наблюдатель')], default='JUDGE', max_length=50, verbose_name='Тип пользователя'),
        ),
    ]
