# Generated by Django 2.1.4 on 2019-01-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_competition_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='competition',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
