# Generated by Django 2.1.4 on 2019-02-11 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20190108_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Участники конкурса'),
        ),
    ]
