# Generated by Django 2.1.7 on 2019-02-19 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_auto_20190213_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judges', to=settings.AUTH_USER_MODEL, verbose_name='Судьи конкурса'),
        ),
    ]
