# Generated by Django 2.1.7 on 2019-02-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_competition_judges'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='place_in_competition',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в конкурсе'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер участника в конкурсе'),
        ),
    ]
